[wokwi]
version = 1
elf = ".pio/build/esp32s3_debug/EasyHelpers-v1.8.1-esp32s3_debug-ee00d5c-main.elf"
firmware = ".pio/build/esp32s3_debug/EasyHelpers-v1.8.1-esp32s3_debug-ee00d5c-main.bin"
[[net.forward]]
from = "localhost:8180"
to = "target:80"
