[wokwi]
version = 1
elf = ".pio/build/esp32dev_debug/EasyHelpers-v1.2.0-esp32dev_debug-50d6edb-main.elf"
firmware = ".pio/build/esp32dev_debug/EasyHelpers-v1.2.0-esp32dev_debug-50d6edb-main.bin"
[[net.forward]]
from = "localhost:8180"
to = "target:80"
