[wokwi]
version = 1
elf = ".pio/build/esp32dev_debug/EasyHelpers-v1.4.0-esp32dev_debug-5dc96f5-main.elf"
firmware = ".pio/build/esp32dev_debug/EasyHelpers-v1.4.0-esp32dev_debug-5dc96f5-main.bin"
[[net.forward]]
from = "localhost:8180"
to = "target:80"
