[wokwi]
version = 1
elf = ".pio/build/esp32s3_debug/EasyHelpers-v1.7.0-esp32s3_debug-fd589a9-main.elf"
firmware = ".pio/build/esp32s3_debug/EasyHelpers-v1.7.0-esp32s3_debug-fd589a9-main.bin"
[[net.forward]]
from = "localhost:8180"
to = "target:80"
