[wokwi]
version = 1
elf = ".pio/build/esp32dev_debug/EasyHelpers-v1.5.0-esp32dev_debug-965d6bd-main.elf"
firmware = ".pio/build/esp32dev_debug/EasyHelpers-v1.5.0-esp32dev_debug-965d6bd-main.bin"
[[net.forward]]
from = "localhost:8180"
to = "target:80"
