[wokwi]
version = 1
elf = ".pio/build/esp32s3_debug/EasyHelpers-v1.6.5-esp32s3_debug-4cb0c40-main.elf"
firmware = ".pio/build/esp32s3_debug/EasyHelpers-v1.6.5-esp32s3_debug-4cb0c40-main.bin"
[[net.forward]]
from = "localhost:8180"
to = "target:80"
